name: Test Project
on: push
# Jobs
jobs:
  # Test Job
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
# Deploy Job
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
